
# config.py

# IMPORTANT: REPLACE THESE PLACEHOLDERS WITH YOUR ACTUAL KEYS!
BOT_TOKEN = "7752535730:AAGQCo2dRI1BjTbWonc0WBhm9ZZik3M4A5A" 
CRYPTOMUS_MERCHANT_ID = "e8a62135-2bf5-450e-a0d1-20afe9dffa6f"
CRYPTOMUS_API_KEY = "YOUR_API_KEY_FROM_CRYPTOMUS"

# Price settings (per key in USD)
KEY_PRICE_USD = 10.00 
# The currency you want the bot to display and use for calculation
CURRENCY = "USD"